# .pep8speaks.yml
#
# Configuration for PEP 8 Speaks GitHub integration

scanner:
  diff_only: False
  linter: pycodestyle

pycodestyle:
  max-line-length: 120    # Override 79 column default, informal widescreen standard
  ignore:
    - E402                # Imports at top of file

no_blank_comment: False   # Make sure things are false for now

